name: Recent Activity
on:
  schedule:
    - cron: "15 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build table rows
        env:
          GHUSER: muneeb-anjum0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/users/${GHUSER}/events/public?per_page=10" > events.json

          jq -r '
            def repo: .repo.name;
            def link:
              if .type=="PullRequestEvent" then .payload.pull_request.html_url
              elif .type=="IssuesEvent" then .payload.issue.html_url
              elif .type=="ReleaseEvent" then .payload.release.html_url
              elif .type=="CreateEvent" and .payload.ref != null then "https://github.com/\(repo)/tree/\(.payload.ref)"
              else "https://github.com/\(repo)" end;
            def act:
              .type
              | sub("Event$"; "")
              | gsub("PullRequest"; "PR")
              | gsub("Issues"; "Issue")
              | gsub("Watch"; "Star")
              | gsub("Create"; "Create")
              | gsub("Push"; "Push")
              | gsub("Release"; "Release")
              | gsub("Fork"; "Fork");
            if length==0 then
              "<tr><td colspan=\"3\"><i>No public activity yet</i></td></tr>"
            else
              [ .[] |
                "<tr><td>" + (.created_at | sub("T"; " ") | sub("Z"; "") | .[0:16]) +
                "</td><td>" + act +
                "</td><td><a href=\"" + link + "\">" + repo + "</a></td></tr>"
              ] | join("\n")
            end
          ' events.json > rows.html

          awk '
            BEGIN {p=1}
            /<!--RECENT_ACTIVITY:start-->/ { print; system("cat rows.html"); p=0; next }
            /<!--RECENT_ACTIVITY:end-->/   { print; p=1; next }
            p { print }
          ' README.md > README.new && mv README.new README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update recent activity"
          branch: main
